# Generated by Django 4.2.6 on 2023-10-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=255)),
                ('unidadAcademica', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=255)),
                ('materia', models.CharField(max_length=255)),
                ('Curso', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=10)),
                ('jornada', models.CharField(max_length=20)),
                ('nrc', models.CharField(max_length=20)),
                ('listaCruzada', models.CharField(max_length=255)),
                ('nrcLigados', models.CharField(max_length=255)),
                ('idListaCurzada', models.IntegerField()),
                ('calificable', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('nombreAsignatura', models.CharField(max_length=255)),
                ('horasAPagar', models.IntegerField()),
                ('tipoActividad', models.CharField(max_length=255)),
                ('modalidad', models.CharField(max_length=20)),
                ('numeroVacantes', models.IntegerField()),
                ('numeroInscritos', models.IntegerField()),
                ('restriccionCodPrograma', models.CharField(max_length=255)),
                ('restriccionDescPrograma', models.CharField(max_length=255)),
                ('restriccionCampus', models.CharField(max_length=255)),
                ('nivelCurso', models.IntegerField()),
                ('unidadQuePaga', models.CharField(max_length=255)),
                ('semestreQuePaga', models.CharField(max_length=20)),
                ('prorcentajeOnline', models.FloatField()),
                ('proveedor', models.CharField(max_length=255)),
                ('administrador', models.CharField(max_length=255)),
                ('iniciativa', models.CharField(max_length=255)),
                ('aulas', models.CharField(max_length=255)),
                ('planificacionAcademica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.planificacionacademica')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.CharField(max_length=255)),
                ('horaFin', models.CharField(max_length=255)),
                ('dia', models.CharField(max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.curso')),
            ],
        ),
    ]
