# Generated by Django 4.2.6 on 2023-11-07 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0011_delete_profesorcurso'),
        ('planificacion', '0004_rename_carrera_secretarioacademico_carrera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curso', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planificacion.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disponibilidad.profesor')),
            ],
        ),
    ]
