# Generated by Django 4.2.6 on 2023-11-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0011_delete_profesorcurso'),
        ('planificacion', '0005_profesorcurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacionacademica',
            name='fechaFin',
        ),
        migrations.RemoveField(
            model_name='planificacionacademica',
            name='fechaInicio',
        ),
        migrations.RemoveField(
            model_name='planificacionacademica',
            name='programa',
        ),
        migrations.AddField(
            model_name='planificacionacademica',
            name='profesor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='disponibilidad.profesor'),
        ),
        migrations.DeleteModel(
            name='ProfesorCurso',
        ),
    ]
