# Generated by Django 4.2.6 on 2023-11-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0006_remove_planificacionacademica_fechafin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='planificacionacademica',
            name='actividad',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='planificacionacademica',
            name='modulos',
            field=models.ManyToManyField(to='planificacion.modulo'),
        ),
    ]
