# Generated by Django 4.2.6 on 2023-11-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0008_remove_planificacionacademica_campus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacionacademica',
            name='modulos',
        ),
    ]
