# Generated by Django 4.2.6 on 2023-11-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0009_remove_planificacionacademica_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacionacademica',
            name='modulos',
            field=models.CharField(default='', max_length=255),
        ),
    ]
