# Generated by Django 4.2.6 on 2023-11-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0010_planificacionacademica_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacionacademica',
            name='modalidad',
            field=models.CharField(default='', max_length=255),
        ),
    ]
