# Generated by Django 4.2.6 on 2023-10-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0003_profesorcurso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfesorCurso',
        ),
    ]
