# Generated by Django 4.2.6 on 2023-10-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_curso_horariocurso'),
        ('disponibilidad', '0004_delete_profesorcurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disponibilidad.profesor')),
            ],
        ),
    ]
