# Generated by Django 4.2.6 on 2023-10-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0005_profesorcurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='tipo',
            field=models.CharField(default='', max_length=45),
        ),
    ]
