# Generated by Django 4.2.6 on 2023-11-01 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_rename_carrera_secretarioacademico_carrera_and_more'),
        ('disponibilidad', '0006_profesor_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesorcurso',
            name='curso',
        ),
        migrations.AddField(
            model_name='profesorcurso',
            name='planificacionAcademica',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planificacion.planificacionacademica'),
        ),
    ]
