# Generated by Django 4.2.6 on 2023-11-04 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0007_remove_profesorcurso_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='tipo',
        ),
    ]
