# Generated by Django 4.2.6 on 2023-11-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0011_delete_profesorcurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='modulosDiurno',
            field=models.CharField(default='[[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0]]', max_length=255),
        ),
        migrations.AddField(
            model_name='profesor',
            name='modulosVespertino',
            field=models.CharField(default='[[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0]]', max_length=255),
        ),
    ]
