# Generated by Django 4.2.6 on 2023-10-29 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rut_cargo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rut',
            new_name='Usuario',
        ),
    ]
